package com.qhiehome.ihome.persistence;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qhiehome.ihome.persistence.MapSearch;

import com.qhiehome.ihome.persistence.MapSearchDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mapSearchDaoConfig;

    private final MapSearchDao mapSearchDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mapSearchDaoConfig = daoConfigMap.get(MapSearchDao.class).clone();
        mapSearchDaoConfig.initIdentityScope(type);

        mapSearchDao = new MapSearchDao(mapSearchDaoConfig, this);

        registerDao(MapSearch.class, mapSearchDao);
    }
    
    public void clear() {
        mapSearchDaoConfig.clearIdentityScope();
    }

    public MapSearchDao getMapSearchDao() {
        return mapSearchDao;
    }

}
